GET https://api.spotify.com/v1/me/player/currently-playing
Authorization: Bearer BQDvOECWmreOuiLsX0umd0EeoOHN8_IsL8fw59q1arYgzy9LLVTT4dNri3GFQ9C4Buk0BM8r-a2hEQZZZttfUP3gBItplKdcp1S3jOEQl0DFRPoCtbR8FlZUvK2M-GfRkQiEycs4DaQxQOJo-JEzklCLE4plFthnkSNv0e29PuwlBheX4iMDI3Yxq4t3KJxIhZPKKqd4VOkJ8PwWIBii3wsjFuncO1L58r8yr6_MpLjfp-548tAATdECQ4K7qjVhKOwJ1hlB0ptzaKUym2rKQOEACJfMHz7ysaBFzVOKm4uvEkLhfDlJ0_EBJDHSzPRh